---

- name: Ensure Python3 and pip3 are installed
  become: true
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Ensure virtualenv is installed
  become: true
  apt:
    name: python3-venv
    state: present

- name: Create a virtual environment
  become: true
  command: python3 -m venv /opt/venv

- name: Install requests in virtual environment
  become: true
  command: /opt/venv/bin/pip install requests

- name: Install psycopg2-binary in virtual environment
  become: true
  command: /opt/venv/bin/pip install psycopg2-binary
