---

- name: Install PostgreSQL
  become: true
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is running
  become: true
  service:
    name: postgresql
    state: started
    enabled: true

- name: Update listen_addresses in postgresql.conf
  become: true
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present
    
- name: Allow external connections in pg_hba.conf
  become: true
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regexp: '^host\s+all\s+all\s+0\.0\.0\.0/0\s+'
    line: "host    all             all             0.0.0.0/0               scram-sha-256"
    state: present

- name: Reload PostgreSQL to apply configuration changes
  become: true
  service:
    name: postgresql
    state: reloaded

- name: Check if PostgreSQL user exists
  become: true
  shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ pg_server_sa_name }}';"
  register: user_exists
  changed_when: false

- name: Create a new PostgreSQL user if it does not exist
  become: true
  shell: |
    sudo -u postgres psql -c "CREATE USER {{ pg_server_sa_name }} WITH PASSWORD '{{ pg_server_sa_password }}';"
  when: user_exists.stdout == ""
  args:
    executable: /bin/bash

- name: Grant superuser privileges to the new user
  become: true
  shell: |
    sudo -u postgres psql -c "ALTER ROLE {{ pg_server_sa_name }} WITH SUPERUSER;"
  args:
    executable: /bin/bash