---

- name: Install PostgreSQL
  become: true
  ansible.builtin.apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running and enabled
  become: true
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Configure PostgreSQL
  become: true
  ansible.builtin.template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_config_dir }}/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0644
  notify: restart postgresql

- name: Configure authentication (pg_hba.conf)
  become: true
  ansible.builtin.template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_dir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0640
  notify: restart postgresql

- name: Set password via psql command
  become: true
  ansible.builtin.shell: |
    sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgresql_superuser_password }}';"