---
- hosts: edu_practice_pg_server
  vars_files:
    - "../inventories/pg_projects/{{ project_name }}.yml"
    - "../roles/pg_server/vars/main.yml"
  tasks:
    - name: Drop project
      include_role:
        name: pg_project
      vars:
        action: drop
        pg_user: "{{ user }}"
        pg_db: "{{ db }}"
        pg_password: "{{ password }}"
        postgres_admin_pass: "{{ pg_server_sa_password }}"

    - name: Archive config file
      ansible.builtin.copy:
        src: "../inventories/pg_projects/{{ project_name }}.yml"
        dest: "../inventories/archive/{{ project_name }}_{{ ansible_date_time.date }}.yml"
        remote_src: no
      delegate_to: localhost

    - name: Remove original config file
      ansible.builtin.file:
        path: "../inventories/pg_projects/{{ project_name }}.yml"
        state: absent
      delegate_to: localhost